#!/bin/bash

# Using 3/4 GB for shared memory
SHARED_MAX=$((768 * 1024 * 1024))
SHARED_ALL=$((768 * 1024 * 1024 / 4096))

echo "=== Preparing system for GAMESS install ==="
echo "Updating apt-get"
apt-get update -qq
echo "Installing build tools"
apt-get install -y gfortran csh xauth git curl
echo "Installing atlas math libraries"
apt-get install -y libblas-dev libatlas-base-dev

# Cloud 9 container does not allow access to sysctl.conf
# and limits are already high
# echo "Setting shmmax to $SHARED_MAX"
# echo "Setting shmall to $SHARED_ALL"
# echo "kernel.shmmax = $SHARED_MAX" >> /etc/sysctl.conf
# echo "kernel.shmall = $SHARED_ALL" >> /etc/sysctl.conf
# sysctl -p

echo "Installing Java runtime and Jmol"
apt-get install -y default-jre jmol
echo "Installing OpenBabel"
apt-get install -y openbabel

chmod u+x build-gamess.sh

